-- 코드를 작성해주세요
SELECT  T1.ITEM_ID
    ,   T1.ITEM_NAME
FROM    ITEM_INFO T1
WHERE   T1.ITEM_ID IN (
    SELECT  ITEM_ID
    FROM    ITEM_TREE TT1
    WHERE   TT1.ITEM_ID = T1.ITEM_ID
        AND TT1.PARENT_ITEM_ID  IS NULL
)
ORDER BY
        T1.ITEM_ID  ASC