-- 코드를 입력하세요
SELECT  LEFT(T1.PRODUCT_CODE, 2)    AS 'CATEGORY'
    ,   COUNT(T1.PRODUCT_ID)        AS 'PRODUCTS'
FROM    PRODUCT T1
GROUP BY
        LEFT(T1.PRODUCT_CODE, 2)
ORDER BY
        LEFT(T1.PRODUCT_CODE, 2)    ASC