SELECT  T2.CATEGORY         AS 'CATEGORY'
    ,   SUM(T1.TOTAL_SALES) AS 'TOTAL_SALES'
FROM (
    SELECT  TT1.BOOK_ID     AS 'BOOK_ID'   
        ,   SUM(TT1.SALES)  AS 'TOTAL_SALES'
    FROM    BOOK_SALES TT1
    WHERE   YEAR(TT1.SALES_DATE)     = 2022
        AND MONTH(TT1.SALES_DATE)    = 1
    GROUP BY
            TT1.BOOK_ID
) T1
JOIN    BOOK T2
    ON  T2.BOOK_ID = T1.BOOK_ID
GROUP BY
        T2.CATEGORY
ORDER BY
        T2.CATEGORY ASC