-- 코드를 입력하세요
SELECT  T1.PRODUCT_ID   AS PRODUCT_ID
    ,   T1.PRODUCT_NAME AS PRODUCT_NAME
    ,   T1.PRODUCT_CD   AS PRODUCT_CD
    ,   T1.CATEGORY     AS CATEGORY
    ,   T1.PRICE        AS PRICE
FROM    FOOD_PRODUCT T1
ORDER BY
        T1.PRICE DESC
LIMIT   1