-- 코드를 입력하세요
SELECT  CART_ID
FROM    CART_PRODUCTS T1
GROUP BY
        T1.CART_ID
HAVING
        COUNT(CASE WHEN NAME = 'Milk' THEN 1 END) > 0
    AND COUNT(CASE WHEN NAME = 'Yogurt' THEN 1 END) > 0
ORDER BY
        T1.CART_ID  ASC