-- 코드를 입력하세요
SELECT  FOOD_TYPE
    ,   T1.REST_ID
    ,   REST_NAME
    ,   FAVORITES
FROM    REST_INFO T1
WHERE   (FOOD_TYPE, FAVORITES) IN (
    SELECT  FOOD_TYPE
        ,   MAX(TT1.FAVORITES)
    FROM    REST_INFO TT1
    WHERE   TT1.FOOD_TYPE IS NOT NULL
    GROUP BY
            TT1.FOOD_TYPE
)
ORDER BY
        T1.FOOD_TYPE    DESC