-- 코드를 작성해주세요
SELECT  ROUTE
    ,   CONCAT(ROUND(SUM(T1.D_BETWEEN_DIST), 1), 'km')  AS 'TOTAL_DISTANCE'
    ,   CONCAT(ROUND(AVG(T1.D_BETWEEN_DIST), 2), 'km')  AS 'AVERAGE_DISTANCE'
FROM    SUBWAY_DISTANCE T1
GROUP BY
        T1.ROUTE
ORDER BY
        ROUND(SUM(T1.D_BETWEEN_DIST), 1)   DESC