-- 코드를 작성해주세요

WITH FRONTEND_SKILLS AS (
    SELECT  TT1.CODE
    FROM    SKILLCODES TT1
    WHERE   TT1.CATEGORY    = 'Front End'
)

SELECT  DISTINCT
        T1.ID
    ,   T1.EMAIL
    ,   T1.FIRST_NAME
    ,   T1.LAST_NAME
FROM    DEVELOPERS T1
JOIN    FRONTEND_SKILLS T2
WHERE   T1.SKILL_CODE & T2.CODE
ORDER BY
        T1.ID   ASC

/*
SELECT  T1.ID
    ,   T1.EMAIL
    ,   T1.FIRST_NAME
    ,   T1.LAST_NAME
FROM    DEVELOPERS T1
WHERE   T1.SKILL_CODE & (
    SELECT  SUM(TT1.CODE)
    FROM    SKILLCODES  TT1
    WHERE   TT1.CATEGORY    = 'Front End'
)
ORDER BY
        T1.ID   ASC
*/