-- 코드를 작성해주세요
SELECT  COUNT(*)    AS FISH_COUNT
FROM    FISH_INFO T1
WHERE   T1.FISH_TYPE IN (
    SELECT  TT1.FISH_TYPE
    FROM    FISH_NAME_INFO TT1
    WHERE   TT1.FISH_NAME IN ('BASS', 'SNAPPER')
)