SELECT  T1.USER_ID
    ,   T1.PRODUCT_ID
FROM
(
SELECT  TT1.USER_ID     AS USER_ID
    ,   TT1.PRODUCT_ID  AS PRODUCT_ID
    ,   COUNT(*)        AS COUNT_
FROM    ONLINE_SALE TT1
GROUP BY
        TT1.USER_ID
    ,   TT1.PRODUCT_ID
) T1
WHERE   T1.COUNT_ >= 2
ORDER BY
        T1.USER_ID      ASC
    ,   T1.PRODUCT_ID   DESC