-- 코드를 작성해주세요
SELECT  YEAR(T1.DIFFERENTIATION_DATE)   AS 'YEAR'
    ,   (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA WHERE YEAR(DIFFERENTIATION_DATE) = YEAR(T1.DIFFERENTIATION_DATE)) - T1.SIZE_OF_COLONY   AS 'YEAR_DEV'
    ,   ID
FROM    ECOLI_DATA T1
ORDER BY
        YEAR(T1.DIFFERENTIATION_DATE)
    ,   YEAR_DEV