-- 코드를 입력하세요
SELECT  T1.FLAVOR   AS 'FLAVOR'
FROM    FIRST_HALF T1
JOIN (
    SELECT  T1.FLAVOR           AS 'FLAVOR'
        ,   SUM(T1.TOTAL_ORDER) AS 'TOTAL_ORDER'
    FROM    JULY T1
    GROUP BY
            T1.FLAVOR
) T2
    ON  T2.FLAVOR   = T1.FLAVOR
ORDER BY
        T1.TOTAL_ORDER + T2.TOTAL_ORDER DESC
LIMIT   3
