-- 코드를 입력하세요
SELECT  T1.ANIMAL_ID    AS 'ANIMAL_ID'
    ,   T1.NAME         AS 'NAME'
FROM    ANIMAL_INS T1
JOIN    ANIMAL_OUTS T2
    ON  T2.ANIMAL_ID    = T1.ANIMAL_ID
WHERE   T2.DATETIME < T1.DATETIME
ORDER BY
        T1.DATETIME ASC