-- 코드를 작성해주세요
SELECT  COUNT(*)  AS 'FISH_COUNT'
    ,   MAX(T1.LENGTH)  AS 'MAX_LENGTH'
    ,   FISH_TYPE
FROM    FISH_INFO T1
GROUP BY
        T1.FISH_TYPE
HAVING  AVG(CASE  WHEN T1.LENGTH IS NOT NULL THEN T1.LENGTH ELSE 10 END) >= 33
ORDER BY
        FISH_TYPE   ASC