-- 코드를 입력하세요
SELECT  T1.CAR_ID
    ,   T1.CAR_TYPE
    ,   ROUND(
            T1.DAILY_FEE * 30 * (100 - CAST(SUBSTRING_INDEX(IFNULL(T2.DISCOUNT_RATE, 0), '%', 1) AS UNSIGNED)) / 100
    )   AS 'FEE'
FROM    CAR_RENTAL_COMPANY_CAR T1
LEFT JOIN    CAR_RENTAL_COMPANY_DISCOUNT_PLAN T2
    ON  T2.CAR_TYPE = T1.CAR_TYPE
    AND T2.DURATION_TYPE    = '30일 이상'
WHERE   T1.CAR_ID   NOT IN (
    SELECT  TT1.CAR_ID
    FROM    CAR_RENTAL_COMPANY_RENTAL_HISTORY TT1
    WHERE   TT1.START_DATE  <= '2022-11-30'
        AND TT1.END_DATE    >= '2022-11-01'
)
GROUP BY
        T1.CAR_ID
HAVING  T1.CAR_TYPE IN ('세단', 'SUV')
    AND FEE BETWEEN 500000 AND 2000000
ORDER BY
    FEE DESC
,   CAR_TYPE    ASC
,   CAR_ID  DESC
        
    
--  CAR_RENTAL_COMPANY_CAR  : 대여중인 자동차
--  CAR_RENTAL_COMPANY_RENTAL_HISTORY   : 대여 기록 정보 (FK: CAR_ID)
--  CAR_RENTAL_COMPANY_DISCOUNT_PLAN    : 할인 정책 정보 (FK: CAR_TYPE)
--  ㄴ T2.START_DATE, T2.END_DATE => T3.DURATION_TYPE