-- 코드를 입력하세요
SELECT  T2.HISTORY_ID
    ,   ROUND(
            T1.DAILY_FEE * (DATEDIFF(T2.END_DATE, T2.START_DATE) + 1) * (100 - CAST(SUBSTRING_INDEX(IFNULL(T3.DISCOUNT_RATE, 0), '%', 1) AS UNSIGNED)) / 100
    )   AS 'FEE'
FROM    CAR_RENTAL_COMPANY_CAR T1
JOIN    CAR_RENTAL_COMPANY_RENTAL_HISTORY T2
    ON  T2.CAR_ID   = T1.CAR_ID
LEFT JOIN    CAR_RENTAL_COMPANY_DISCOUNT_PLAN T3
    ON  T3.CAR_TYPE = T1.CAR_TYPE
    AND T3.DURATION_TYPE    = (
        CASE 
            WHEN DATEDIFF(T2.END_DATE, T2.START_DATE) + 1 >= 90  THEN '90일 이상'
            WHEN DATEDIFF(T2.END_DATE, T2.START_DATE) + 1 >= 30  THEN '30일 이상'
            WHEN DATEDIFF(T2.END_DATE, T2.START_DATE) + 1 >= 7   THEN '7일 이상'
            ELSE ''
        END
    )
WHERE   T1.CAR_TYPE = '트럭'
ORDER BY
        FEE             DESC
    ,   T2.HISTORY_ID   DESC

-- 대여중인 자동차 정보 : CAR_RENTAL_COMPANY_CAR
-- 대여 기록 정보 : CAR_RENTAL_COMPANY_RENTAL_HISTORY (FK: CAR_RENTAL_COMPANY_CAR.CAR_ID)
-- 자동차 종류별/대여기간 종류별 할인 정보 : CAR_RENTAL_COMPANY_DISCOUNT_PLAN (FK: CAR_RENTAL_COMPANY_CAR.CAR_TYPE)