-- 코드를 입력하세요
SELECT  T2.PRODUCT_CODE                 AS 'PRODUCT_CODE'
    ,   SUM(T1.SALES_AMOUNT) * T2.PRICE AS 'SALES'
FROM    OFFLINE_SALE T1
JOIN    PRODUCT T2
    ON  T2.PRODUCT_ID = T1.PRODUCT_ID
GROUP BY
        T2.PRODUCT_CODE
ORDER BY
        SUM(T1.SALES_AMOUNT) * T2.PRICE DESC
    ,   T2.PRODUCT_CODE                 ASC