-- 코드를 작성해주세요
SELECT  T1.ID       AS ID
    ,   T1.GENOTYPE AS GENOTYPE
    ,   T2.GENOTYPE AS PARENT_GENOTYPE
FROM    ECOLI_DATA T1
JOIN    ECOLI_DATA T2
    ON  T2.ID   = T1.PARENT_ID
WHERE   T1.GENOTYPE | T2.GENOTYPE = T1.GENOTYPE
ORDER BY
        T1.ID   ASC