-- 코드를 입력하세요
SELECT  T1.USER_ID  AS 'USER_ID'
    ,   T1.NICKNAME AS 'NICKNAME'
    ,   CONCAT(T1.CITY, ' ', T1.STREET_ADDRESS1, ' ', T1.STREET_ADDRESS2) AS '전체주소'
    ,   CONCAT(SUBSTRING(T1.TLNO, 1, 3), '-', SUBSTRING(T1.TLNO, 4, 4), '-', SUBSTRING(T1.TLNO, 8)) AS '전화번호'
FROM    USED_GOODS_USER T1
JOIN    USED_GOODS_BOARD T2
    ON  T2.WRITER_ID    = T1.USER_ID
GROUP BY
        T1.USER_ID
HAVING  COUNT(*)    >= 3
ORDER BY
        T1.USER_ID  DESC

-- 중고 거래 게시판 : USED_GOODS_BOARD
-- 중고 거래 게시판 첨부파일(?) : USED_GOODS_USER