-- 코드를 입력하세요
SELECT  T1.FACTORY_ID   AS FACTORY_ID
    ,   T1.FACTORY_NAME AS FACTORY_NAME
    ,   T1.ADDRESS      AS ADDRESS
FROM    FOOD_FACTORY T1
WHERE   T1.ADDRESS LIKE '%강원도%'
ORDER BY
        T1.FACTORY_ID ASC