-- 코드를 입력하세요
SELECT  HOUR(DATETIME)  AS HOUR
    ,   COUNT(*)        AS COUNT
FROM    ANIMAL_OUTS T1
WHERE   9 <= HOUR(T1.DATETIME)
    AND HOUR(T1.DATETIME) < 20
GROUP BY
    HOUR(T1.DATETIME)
ORDER BY
    HOUR ASC