-- 코드를 작성해주세요
SELECT  T1.ITEM_ID      AS 'ITEM_ID'
    ,   T1.ITEM_NAME    AS 'ITEM_NAME'
    ,   T1.RARITY       AS 'RARITY'
FROM    ITEM_INFO T1
WHERE   T1.ITEM_ID NOT IN (
    SELECT  TT1.PARENT_ITEM_ID
    FROM    ITEM_TREE TT1
    WHERE   TT1.PARENT_ITEM_ID IS NOT NULL
)
ORDER BY
        T1.ITEM_ID  DESC